plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-cayman
include:
  - .well-known
title: Read interesting convos
tagline: Invite-only texting that anyone can read
url: https://www.getponder.com
description: Invite-only texting that anyone can read
#image: /assets/image/Icon-1024-borderless.png
