plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-cayman
include:
  - .well-known
title: Ponder
tagline: Invite-only convos that anyone can read
url: https://www.getponder.com
description: Buckle up. It's ready.
image:
